version: '3.8'

services:
  fen_tool:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./data/inputs:/data/inputs
      - ./data/outputs:/data/outputs
    ports:
      - "8080:8080"
    command: ["python", "main.py"]